-- New profile fields
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS languages TEXT[] DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS pronouns TEXT DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender_identity TEXT DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS relationship_type TEXT DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS exercise TEXT DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS education TEXT DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS profession TEXT DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS religion TEXT DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS music_genres TEXT[] DEFAULT NULL;

-- New discovery filter columns
ALTER TABLE discovery_preferences
  ADD COLUMN IF NOT EXISTS gender_identity TEXT[] DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS gender_identity_include_unspecified BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS languages TEXT[] DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS pronouns TEXT[] DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS relationship_type TEXT[] DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS exercise TEXT[] DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS education TEXT[] DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS religion TEXT[] DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS music_genres TEXT[] DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS languages_include_unspecified BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS pronouns_include_unspecified BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS relationship_type_include_unspecified BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS exercise_include_unspecified BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS education_include_unspecified BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS religion_include_unspecified BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS music_genres_include_unspecified BOOLEAN DEFAULT TRUE;
